### ISSUE TITLE
TxDelay Config Value kann nicht in int gewandelt werden

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/SDRPager#35]
Aktueller master-branch
````
linux:/opt/SDRPager/raspager-sdr/target # java -jar raspager-sdr-2.0.0-SNAPSHOT.jar -s -c /etc/funkrufslave_DB0SDA.conf
Experimental:  JNI_OnLoad called.
Feb 28, 2017 3:38:34 PM de.rwth_aachen.afu.raspager.Main main
SEVERE: Main application error.
java.lang.NumberFormatException: For input string: "txDelay"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at de.rwth_aachen.afu.raspager.Configuration.getInt(Configuration.java:184)
        at de.rwth_aachen.afu.raspager.Scheduler.<init>(Scheduler.java:40)
        at de.rwth_aachen.afu.raspager.RasPagerService.startScheduler(RasPagerService.java:82)
        at de.rwth_aachen.afu.raspager.RasPagerService.startServer(RasPagerService.java:139)
        at de.rwth_aachen.afu.raspager.RasPagerService.run(RasPagerService.java:227)
        at de.rwth_aachen.afu.raspager.Main.main(Main.java:110)

linux:/opt/SDRPager/raspager-sdr/target #
````

Config-File:
````
linux:/opt/SDRPager/raspager-sdr/target # cat /etc/funkrufslave_DB0SDA.conf
#Tue Feb 28 15:11:08 CET 2017
invert=false
sdr.device=Intel [plughw\:0,0]
net.masters=44.225.164.2
gpio.raspirev=RaspberryPi_B_Rev1
serial.pin=RTS
serial.use=true
sdr.correction=0.59
net.port=1337
serial.port=/dev/ttyS1
gpio.use=false
gpio.pin=GPIO 0
txDelay=50
linux:/opt/SDRPager/raspager-sdr/target #
````

**Comment by dh3wr** [comment]
Geht. Danke!
